# Generated by Django 3.1 on 2020-11-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201114_2149'),
        ('users', '0002_auto_20201029_2016'),
    ]

    operations = [
    ]
